Update OpenAPI Linter for supporting v0.36 and later
pinterest/arcanist-linters pull request #68
Opened 2021-04-02 23:14 UTC by meetnick

- Output process functions is updated to support version v0.36 and later
- Updated Sample Output according to versions greater than v0.36

2021-04-02 23:17 UTC, steverice requested changes
There are some references in the README to version 0.34.1 (our previous minimum version).

Please update these as well.

2021-04-02 23:24 UTC, meetnick commented
I just saw this! Done.

2021-04-02 23:25 UTC, steverice approved these changes
Thanks for the update! For reference, this is the change that modified the output format: https://github.com/IBM/openapi-validator/pull/260#issuecomment-794236330

2021-04-03 00:13 UTC, jparise approved these changes

2021-04-03 00:14 UTC, merged